
services:
  frontend:
    build:
      context: ./frontend  # This tells Docker to look in the frontend directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # Mount for hot reloading
      - /app/node_modules  # Prevents overwriting node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    ports:
      - "5001:5000"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nba_betting
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: